---
name: upload OpenTelemetry collector config to S3

on:
  workflow_call:
  repository_dispatch:
    types: [trigger-ecspresso]

jobs:
  put-otelcol-config:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload stg/otelcol-config.yaml to S3
        run: aws --region ap-northeast-1 s3 cp otelcol-config/stg/ s3://dreamkast-otelcol-config/stg/ --recursive

      - name: Upload prod/otelcol-config.yaml to S3
        run: aws --region ap-northeast-1 s3 cp otelcol-config/prod/ s3://dreamkast-otelcol-config/prod/ --recursive
